---
vMX1:
    hostname: 192.168.20.111
    groups:
        - junos_group
    data:
        host_name: "vmx1"
        lan: "lan"
        ospf_int:
            ge-0/0/3.0:
                isActive: True
                ospf_area: '0.0.0.0'
            ge-0/0/1.0:
                ospf_area: '0.0.0.0'
                net_type: 'p2p'
                auth_pw: 'md5keyhere'
                bfd: True
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.0'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.13.1/24'
            lo0:
                ipv4_address: '1.1.1.1/32'
            ge-0/0/1:
                ipv4_address: '192.168.12.1/24'
            ge-0/0/2:
                ipv4_address: '192.168.15.1/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0000.0000.0000.0001.00
            ge-0/0/1.0:
                isActive: True
                level: 2
            ge-0/0/2.0:
                isActive: True
                level: 2
            ge-0/0/3.0:
                isActive: True
                level: 2
vMX2:
    hostname: 192.168.20.112
    groups:
        - junos_group
    data:
        host_name: "vmx2"
        lan: "lan"
        ospf_int:
            ge-0/0/3.0:
                isActive: True
                ospf_area: '0.0.0.0'
            ge-0/0/1.0:
                ospf_area: '0.0.0.0'
                net_type: 'p2p'
                auth_pw: 'md5keyhere'
                bfd: True
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.0'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.10.2/30'
            lo0:
                ipv4_address: '2.2.2.2/32'
            ge-0/0/1:
                ipv4_address: '192.168.12.2/24'
            ge-0/0/2:
                ipv4_address: '192.168.26.2/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0000.0000.0000.0002.00
            ge-0/0/1.0:
                isActive: True
                level: 2
            ge-0/0/2.0:
                isActive: True
                level: 2
            ge-0/0/3.0:
                isActive: True
                level: 2
vMX3:
    hostname: 192.168.20.113
    groups:
        - junos_group
    data:
        host_name: "vmx3"
        lan: "lan"
        ospf_int:
            ge-0/0/3.0:
                isActive: True
                ospf_area: '0.0.0.0'
            ge-0/0/1.0:
                isActive: True
                ospf_area: '0.0.0.0'
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.0'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.13.3/24'
            lo0:
                ipv4_address: '3.3.3.3/32'
            ge-0/0/1:
                ipv4_address: '192.168.34.3/24'
            ge-0/0/2:
                ipv4_address: '192.168.43.3/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0000.0000.0000.0003.00
            ge-0/0/1.0:
                isActive: True
                level: 2
            ge-0/0/2.0:
                isActive: True
                level: 2
            ge-0/0/3.0:
                isActive: True
                level: 2
vMX4:
    hostname: 192.168.20.114
    groups:
        - junos_group
    data:
        host_name: "vmx4"
        lan: "lan"
        ospf_int:
            ge-0/0/3.0:
                isActive: True
                ospf_area: '0.0.0.0'
            ge-0/0/1.0:
                isActive: True
                ospf_area: '0.0.0.0'
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.0'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.10.1/30'
            lo0:
                ipv4_address: '4.4.4.4/32'
            ge-0/0/1:
                ipv4_address: '192.168.34.4/24'
            ge-0/0/2:
                ipv4_address: '192.168.43.4/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0000.0000.0000.0004.00
            ge-0/0/1.0:
                isActive: True
                level: 2
            ge-0/0/2.0:
                isActive: True
                level: 2
            ge-0/0/3.0:
                isActive: True
                level: 2
vMX5:
    hostname: 192.168.20.115
    groups:
        - junos_group
    data:
        host_name: "vmx5"
        lan: "lan"
        ospf_int:
            ge-0/0/1.0:
                isActive: True
                ospf_area: '0.0.0.1'
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.0'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.1'
        node_type: 'router'
        interfaces:
            lo0:
                ipv4_address: '5.5.5.5/32'
            ge-0/0/1:
                ipv4_address: '172.16.57.5/24'
            ge-0/0/2:
                ipv4_address: '192.168.15.5/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0001.0000.0000.0005.00
            ge-0/0/1.0:
                isActive: True
                level: 12
            ge-0/0/2.0:
                isActive: True
                level: 12
            ge-0/0/3.0:
                isActive: True
                level: 12
vMX6:
    hostname: 192.168.20.116
    groups:
        - junos_group
    data:
        host_name: "vmx6"
        lan: "lan"
        ospf_int:
            ge-0/0/1.0:
                isActive: True
                ospf_area: '0.0.0.2'
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.0'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.2'
        node_type: 'router'
        interfaces:
            lo0:
                ipv4_address: '6.6.6.6/32'
            ge-0/0/1:
                ipv4_address: '10.15.68.6/24'
            ge-0/0/2:
                ipv4_address: '192.168.26.6/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0002.0000.0000.0006.00
            ge-0/0/1.0:
                isActive: True
                level: 12
            ge-0/0/2.0:
                isActive: True
                level: 12
            ge-0/0/3.0:
                isActive: True
                level: 12
vMX7:
    hostname: 192.168.20.117
    groups:
        - junos_group
    data:
        host_name: "vmx7"
        lan: "lan"
        ospf_int:
            ge-0/0/1.0:
                isActive: True
                ospf_area: '0.0.0.1'
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.1'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.1'
        node_type: 'router'
        interfaces:
            lo0:
                ipv4_address: '7.7.7.7/32'
            ge-0/0/1:
                ipv4_address: '172.16.57.7/24'
            ge-0/0/2:
                ipv4_address: '172.16.7.1/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0001.0000.0000.0004.00
            ge-0/0/1.0:
                isActive: True
                level: 1
            ge-0/0/2.0:
                isActive: True
                level: 1
            ge-0/0/3.0:
                isActive: True
                level: 1
vMX8:
    hostname: 192.168.20.118
    groups:
        - junos_group
    data:
        host_name: "vmx8"
        lan: "lan"
        ospf_int:
            ge-0/0/1.0:
                isActive: True
                ospf_area: '0.0.0.2'
            ge-0/0/2.0:
                isActive: True
                ospf_area: '0.0.0.2'
            lo0.0:
                isActive: True
                ospf_area: '0.0.0.2'
        node_type: 'router'
        interfaces:
            lo0:
                ipv4_address: '8.8.8.8/32'
            ge-0/0/1:
                ipv4_address: '10.15.68.8/24'
            ge-0/0/2:
                ipv4_address: '10.15.8.1/24'
        isis_int:
            lo0.0:
                isActive: True
                net: 49.0002.0000.0000.0004.00
            ge-0/0/1.0:
                isActive: True
                level: 1
            ge-0/0/2.0:
                isActive: True
                level: 1
            ge-0/0/3.0:
                isActive: True
                level: 1
vMX-PE1:
    hostname: 192.168.20.211
    groups:
        - junos_group
    data:
        node_type: 'PE'
        mc_lag: True
        mc_lag_int: 'ge-0/0/1'
        mc_conf:
            mode: 'active-standby'
            control: 'active'
            chassis_id: '0'
        lacp_conf:
            sys_id: 64:0e:94:28:02:c0
            admin_key: 1
        iccp_conf:
            local_ip: '6.6.6.6'
            peer_ip: '3.3.3.3'
        cust_vlans:
            vlan_id: 500
vMX-PE2:
    hostname: 192.168.20.212
    groups:
        - junos_group
    data:
        node_type: 'PE'
        mc_lag: True
        mc_lag_int: 'ge-0/0/1'
        mc_conf:
            mode: 'active-standby'
            control: 'standby'
            chassis_id: '1'
        lacp_conf:
            sys_id: 64:0e:94:28:02:c0
            admin_key: 1
        iccp_conf:
            local_ip: '3.3.3.3'
            peer_ip: '6.6.6.6'
        cust_vlans:
            vlan_id: 500