---
inventory:
    plugin: YAMLInventory
    options:
        host_file: '/Users/aramide/PycharmProjects/CodeSamples/multiareaOSPF/hosts/hosts.yml'
        group_file: '/Users/aramide/PycharmProjects/CodeSamples/multiareaOSPF/groups/groups.yml'
        defaults_file: '/Users/aramide/PycharmProjects/CodeSamples/multiareaOSPF/defaults/defaults.yml'

runner:
    plugin: threaded
    options:
        num_workers: 10