---

CSR1:
    hostname: 192.168.20.134
    groups:
        - cisco_group

CSR2:
    hostname: 192.168.20.135
    groups:
        - cisco_group
R1:
    hostname: 192.168.20.10
    groups:
        - junos_group
    data:
        ospf_int_1: {'0.0.0.1': ['ge-0/0/0.0', 'ge-0/0/2.0', 'lo0.0'] }
        node_type: 'router'
        interfaces:
            ge-0/0/0:
                ipv4_address: '10.1.12.1/24'
            ge-0/0/2:
                ipv4_address: '10.1.15.1/24'
            ge-0/0/7:
                ipv4_address: '192.168.20.10/24'
            lo0:
                ipv4_address: '1.1.1.1/32'
R2:
    hostname: 192.168.20.11
    groups:
        - junos_group
    data:
        ospf_int_1: {'0.0.0.1': ['ge-0/0/0.0'],
                     '0.0.0.0': ['ge-0/0/3.0', 'ge-0/0/1.0', 'ge-0/0/4.0', 'lo0.0']}
        node_type: 'router'
        interfaces:
            ge-0/0/0:
                ipv4_address: '10.1.12.2/24'
            ge-0/0/1:
                ipv4_address: '10.1.23.1/24'
            ge-0/0/3:
                ipv4_address: '10.1.25.1/24'
            ge-0/0/4:
                ipv4_address: '10.1.26.1/24'
            ge-0/0/7:
                ipv4_address: '192.168.20.11/24'
            lo0:
                ipv4_address: '2.2.2.2/32'
R3:
    hostname: 192.168.20.12
    groups:
        - junos_group
    data:
        ospf_int_1: {'0.0.0.2': ['ge-0/0/2.0'],
                     '0.0.0.0': ['ge-0/0/1.0', 'ge-0/0/0.0', 'ge-0/0/3.0', 'lo0.0']}
        node_type: 'router'
        interfaces:
            ge-0/0/0:
                ipv4_address: '10.1.35.1/24'
            ge-0/0/1:
                ipv4_address: '10.1.23.2/24'
            ge-0/0/2:
                ipv4_address: '10.1.34.1/24'
            ge-0/0/3:
                ipv4_address: '10.1.36.1/24'
            ge-0/0/7:
                ipv4_address: '192.168.20.12/24'
            lo0:
                ipv4_address: '3.3.3.3/32'
R4:
    hostname: 192.168.20.13
    groups:
        - junos_group
    data:
        ospf_int_1: {'0.0.0.2': ['ge-0/0/6.0', 'ge-0/0/2.0', 'lo0.0'] }
        node_type: 'router'
        interfaces:
            ge-0/0/6:
                ipv4_address: '10.1.64.2/24'
            ge-0/0/2:
                ipv4_address: '10.1.34.2/24'
            ge-0/0/7:
                ipv4_address: '192.168.20.13/24'
            lo0:
                ipv4_address: '4.4.4.4/32'
R5:
    hostname: 192.168.20.14
    groups:
        - junos_group
    data:
        ospf_int_1: {'0.0.0.1': ['ge-0/0/2.0'],
                     '0.0.0.0': ['ge-0/0/0.0', 'ge-0/0/1.0', 'ge-0/0/3.0', 'lo0.0']}
        node_type: 'router'
        interfaces:
            ge-0/0/0:
                ipv4_address: '10.1.35.2/24'
            ge-0/0/1:
                ipv4_address: '10.1.56.1/24'
            ge-0/0/2:
                ipv4_address: '10.1.15.2/24'
            ge-0/0/3:
                ipv4_address: '10.1.25.2/24'
            ge-0/0/7:
                ipv4_address: '192.168.20.14/24'
            lo0:
                ipv4_address: '5.5.5.5/32'
R6:
    hostname: 192.168.20.15
    groups:
        - junos_group
    data:
        ospf_int_1: {'0.0.0.2': ['ge-0/0/6.0'],
                     '0.0.0.0': ['ge-0/0/3.0', 'ge-0/0/1.0', 'ge-0/0/4.0', 'lo0.0']}
        node_type: 'router'
        interfaces:
            ge-0/0/6:
                ipv4_address: '10.1.64.1/24'
            ge-0/0/1:
                ipv4_address: '10.1.56.2/24'
            ge-0/0/3:
                ipv4_address: '10.1.36.2/24'
            ge-0/0/4:
                ipv4_address: '10.1.26.2/24'
            ge-0/0/7:
                ipv4_address: '192.168.20.15/24'
            lo0:
                ipv4_address: '6.6.6.6/32'